
CREATE TABLE spots
(
    id INTEGER PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    name VARCHAR(50) NOT NULL,
    longitude DOUBLE PRECISION,
    latitude DOUBLE PRECISION,
    facing DOUBLE PRECISION
);

CREATE TABLE users (
    id pg_catalog.uuid PRIMARY KEY NOT NULL,
    username TEXT NOT NULL,
    password TEXT NOT NULL,
    role TEXT NOT NULL
);

CREATE TABLE events (
   id INTEGER PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
   name TEXT NOT NULL,
   description TEXT NOT NULL,
   date TIMESTAMP
);

-- CREATE TABLE feedbacks (
--    id INTEGER PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
--    spot_id INTEGER
-- );

CREATE TABLE comments
(
    id INTEGER PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    text TEXT NOT NULL ,
    user_id uuid,
    spot_id INTEGER,
    date TIMESTAMP
);

CREATE TABLE conditions
(
    id INTEGER PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    wind_direction INTEGER,
    wind_speed INTEGER,
    rating INTEGER,
    spot_id INTEGER
);



ALTER TABLE comments
    ADD CONSTRAINT fk_user_comment
        FOREIGN KEY (user_id)
            REFERENCES users (id);

ALTER TABLE comments
    ADD CONSTRAINT fk_spot_comment
        FOREIGN KEY (spot_id)
            REFERENCES spots (id);

ALTER TABLE conditions
    ADD CONSTRAINT fk_spot_condition
        FOREIGN KEY (spot_id)
            REFERENCES spots (id);


